log_file: app.log

# Add other configuration settings here
event_extraction_rules:
  event_name:
  date_time:
  organizer:
  location:
gemini_api_key: ""
deduplication_rules:
recurring_event_rules: